### ISSUE TITLE
Is SAIL dataset available?

### ISSUE THREAD

**Issue by qshi95** [dpfried/pragmatic-instructions#1]
Thanks for your great work. I'd like to know if SAIL dataset available?

**Comment by dpfried** [comment]
Thanks for your interest! Yes the SAIL dataset is available here: https://www.cs.utexas.edu/~ml/clamp/navigation/ . 

I haven't released the code for our SAIL experiments from the paper (it's a separate code base and the code is a bit of a mess) but if the SAIL code might be helpful for you please let me know and I'm happy to.

**Comment by qshi95** [comment]
I'll try to understand the data firstly. Thanks for your reply.
